### PR TITLE
Fix issue in has_helpers

### PR DESCRIPTION
**Pull request by rehandalal**
@jsocol r?

### CODE REVIEW

**Comment by jsocol** [comment]
@rehandalal any progress on the py3k part?

**Comment by rehandalal** [comment]
@jsocol sorry! decided to just use this as-is (working only for py 2.7) on Kitsune since we just need it as a stop gap and I was running out of time. will try and get back to this when I have a little bit more time.

**Comment by jsocol** [comment]
@rehandalal I think this was fixed by #77. Mind giving it a shot with master?

**Comment by rehandalal** [comment]
yep! closing in favor of #77

**Pull request closed without merging**
